

CREATE PROCEDURE GetDataListRTG(
@date dateTime

)
AS
BEGIN

SELECT * FROM(

SELECT * FROM OutputTable WHERE tableDate = CONVERT(VARCHAR(10),@date,112)  AND tableType ='RTG'
UNION ALL
SELECT 999999998 id
,tableDate
,tableType
,'Total Day' timebands 
,'' programNTV
,'' programHABERTURK
,'' programCNNTURK
,TotalNTV
,TotalHABERTURK
,TotalCNNTURK
,TotalHALKTV
,TotalKRT
,TotalAHABER
,TotalTRTHABER
,TotalTELE1
,TotalTV100
,TotalHABERGLOBAL
,TotalSOZCUTV
,ABSESNTV
,ABSESHABERTURK
,ABSESCNNTURK
,ABSESHALKTV
,ABSESKRT
,ABSESAHABER
,ABSESTRTHABER
,ABSESTELE1
,ABSESTV100
,ABSESHABERGLOBAL
,ABSESSOZCUTV 
FROM TotalDay WHERE tableDate = CONVERT(VARCHAR(10),@date,112)  AND tableType ='RTG'

UNION ALL
SELECT 999999999 id
,tableDate
,tableType
,'Sýralama' timebands 
,'' programNTV
,'' programHABERTURK
,'' programCNNTURK
,RankTotalNTV TotalNTV
,RankTotalHABERTURK TotalHABERTURK
,RankTotalCNNTURK TotalCNNTURK
,RankTotalHALKTV TotalHALKTV
,RankTotalKRT TotalKRT
,RankTotalAHABER TotalAHABER
,RankTotalTRTHABER TotalTRTHABER
,RankTotalTELE1 TotalTELE1
,RankTotalTV100 TotalTV100
,RankTotalHABERGLOBAL TotalHABERGLOBAL
,RankTotalSOZCUTV TotalSOZCUTV
,RankABSESNTV ABSESNTV
,RankABSESHABERTURK ABSESHABERTURK
,RankABSESCNNTURK ABSESCNNTURK
,RankABSESHALKTV ABSESHALKTV
,RankABSESKRT ABSESKRT
,RankABSESAHABER ABSESAHABER
,RankABSESTRTHABER ABSESTRTHABER
,RankABSESTELE1 ABSESTELE1
,RankABSESTV100 ABSESTV100
,RankABSESHABERGLOBAL ABSESHABERGLOBAL
,RankABSESSOZCUTV  ABSESSOZCUTV 
FROM TotalDay WHERE tableDate = CONVERT(VARCHAR(10),@date,112) AND tableType ='RTG'
) C
ORDER BY C.tableDate, C.tableType,C.id

END




CREATE PROCEDURE GetDataListShare(
@date dateTime

)
AS
BEGIN

SELECT * FROM(

SELECT * FROM OutputTable WHERE tableDate = CONVERT(VARCHAR(10),@date,112)  AND tableType ='SHARE'
UNION ALL
SELECT 999999998 id
,tableDate
,tableType
,'Total Day' timebands 
,'' programNTV
,'' programHABERTURK
,'' programCNNTURK
,TotalNTV
,TotalHABERTURK
,TotalCNNTURK
,TotalHALKTV
,TotalKRT
,TotalAHABER
,TotalTRTHABER
,TotalTELE1
,TotalTV100
,TotalHABERGLOBAL
,TotalSOZCUTV
,ABSESNTV
,ABSESHABERTURK
,ABSESCNNTURK
,ABSESHALKTV
,ABSESKRT
,ABSESAHABER
,ABSESTRTHABER
,ABSESTELE1
,ABSESTV100
,ABSESHABERGLOBAL
,ABSESSOZCUTV 
FROM TotalDay WHERE tableDate = CONVERT(VARCHAR(10),@date,112)  AND tableType ='SHARE'

UNION ALL
SELECT 999999999 id
,tableDate
,tableType
,'Sýralama' timebands 
,'' programNTV
,'' programHABERTURK
,'' programCNNTURK
,RankTotalNTV TotalNTV
,RankTotalHABERTURK TotalHABERTURK
,RankTotalCNNTURK TotalCNNTURK
,RankTotalHALKTV TotalHALKTV
,RankTotalKRT TotalKRT
,RankTotalAHABER TotalAHABER
,RankTotalTRTHABER TotalTRTHABER
,RankTotalTELE1 TotalTELE1
,RankTotalTV100 TotalTV100
,RankTotalHABERGLOBAL TotalHABERGLOBAL
,RankTotalSOZCUTV TotalSOZCUTV
,RankABSESNTV ABSESNTV
,RankABSESHABERTURK ABSESHABERTURK
,RankABSESCNNTURK ABSESCNNTURK
,RankABSESHALKTV ABSESHALKTV
,RankABSESKRT ABSESKRT
,RankABSESAHABER ABSESAHABER
,RankABSESTRTHABER ABSESTRTHABER
,RankABSESTELE1 ABSESTELE1
,RankABSESTV100 ABSESTV100
,RankABSESHABERGLOBAL ABSESHABERGLOBAL
,RankABSESSOZCUTV  ABSESSOZCUTV 
FROM TotalDay WHERE tableDate = CONVERT(VARCHAR(10),@date,112) AND tableType ='SHARE'
) C
ORDER BY C.tableDate, C.tableType,C.id

END




--EXEC sp_spaceused


Exec GetDataListRTG '20240219'
Exec GetDataListShare '20240212'